export const projects = [
  {
    title: 'NFT Marketplace Showcase',
    description: "A landing page for the NFT Marketplace Application. All details about the app are shared in this smooth single page website, together with the download link as well as all the app features. The page is hosted on IPFS, a completely decentralized peer-to-peer protocol. ",
      image: '/images/1.png',
      tags: ['React', 'Javascript'],
    source: 'https://github.com/MwauratheAlex/NFTMarketplaceShowcase.git',
    visit: 'https://nftmarketplaceshowcase.on.fleek.co/',
    id: 0,
  },
  {
    title: 'NFT Marketplace App',
    description: "A modern cross-platform React Native Application with a Sleek and Modern UI. Users can see and search through listed NFTs and scroll through them. The beautiful NFT details page allows users to see more information about a specific NFT and see all it's active bids.",
    image: '/images/4.jpg',
    tags: ['React Native', 'JavaScript'],
    source: 'https://github.com/MwauratheAlex/NFTMarketplace.git',
    visit: 'https://nftmarketplaceshowcase.on.fleek.co/',
    id: 3,
  },
  {
    title: 'Startup Landing Page',
    description:"A fully functional, mobile responsive, beautiful, single page website built using Next Js. Using this landing page will surely drive more traffic to your startup.",
    image: '/images/2.png',
    tags: ['Next Js', 'JavaScript'],
    source: 'https://github.com/MwauratheAlex/nextjs_landing_page',
    visit: 'https://business-landing-page-mwaura.netlify.app/',
    id: 1,
  },
  {
    title: 'Movieland',
    description: "A fully mobile-responsive React JS Application that displays movies and allows users to search for any movie on the internet.",
      image: '/images/3.jpg',
      tags: ['React', 'JavaScript'],
    source: 'https://github.com/MwauratheAlex/movieLand-react.git',
    visit: 'https://movie-land-mwaura.netlify.app/',
    id: 2,
  },
  {
    title: 'GPT-3',
    description: "A fully responsive GPT-3 website/landing page with modern UI/UX following a Figma design built with React.",
      image: '/images/5.png',
      tags: ['React', 'JavaScript', 'Figma'],
    source: 'https://github.com/MwauratheAlex/gpt3.git',
    visit: 'https://gpt-3-mwaura.netlify.app/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Graduated from the Alliance High School, Kenya', },
  { year: 2017, text: 'Joined JKUAT, B.Sc. Electrical and Electronics Engineering', },
  { year: 2018, text: 'Started my developer journey', },
  { year: 2019, text: 'Interned at Makomboki Tea Factory as an Electric Engineer', },
  { year: 2020, text: 'Worked as a freelancer developer', },
  { year: 2021, text: 'Interned at Kenya Power and Lighting Company (KPLC) as an Electric Engineer', },
  { year: 2021, text: 'Interned at Psalmchmart Ltd, Juja, Kenya as an Electronics and Automation Engineer', },
];